### ISSUE TITLE
Build question

### ISSUE THREAD

**Issue by todlandis** [brampf/fitskit#1]
FITSKit commit 187dc49d isn't building for me.  The problem is at line 73 in AnyImageHDU
       self.set(width: Int(buffer.width), height: Int(buffer.height), layers: 3, dataLayout: .UINT8, data: data)

Maybe the last FITSCore commit eliminated set() with the signature it wants?

**Comment by brampf** [comment]
I forgot to push FITSKit along the last FITSCore commit.
