### ISSUE TITLE
Support for RGGB pixel format from an astrophotography camera (ASI, using a Sony color chip)

### ISSUE THREAD

**Issue by brampf** [brampf/fitskit#4]
Next challenge ... My FITS images are in the RGGB pixel format from an astrophotography camera (ASI, using a Sony color chip).

1) I like to convert the FITS with either CoreImage or with CVPixelBufferCreate... to a raw image in order to apply all the nice RawFilters from iOS/Swift to them.

I'm completely stuck. I can create a pixel buffer with the kCVPixelFormaType_14Bayer_RGGB, but the quickview in XCode only shows me a grayscale image. I am not able to convert it to a CIImage or CGImage showing colors, it is either nil or remains a grayscale image that is not de-bayered / demosaiced.

2) Looking at your RGB conversion of the FITS (FITSBytesTool), I noticed the RGB are consecutively ordered (3x layersize). This is not the case for me, where I have a Bayer matrix. Re-writing this function to separate the pixel colors, does result in a color image, but the colors are all wrong...

Any hint to solve either problem would be highly appreciated.

_Originally posted by @Planet30 in https://github.com/brampf/fitscore/discussions/8#discussioncomment-346832_

**Comment by todlandis** [comment]
Hi,  If possible I'd like a Testflight invite, too.  I just bought a ZWO camera for a 6" telescope, and I'm figuring out how to work it.     I'm also interested in displaying the location of FITS images on something like the planetarium view in "Hello Universe", which is free in the App Store.  - Tod

**Comment by brampf** [comment]
Hi Tod! 
Simply send my your Apple ID (dev@brampf.de) and I'll send you an Testflight invitation. 
I created a new thread for you to leave your thoughts and feedback: https://github.com/brampf/fitskit/discussions/6

**Comment by Planet30** [comment]
> Before moving to iPad project, I felt the urge to clean up and make the new code of the advanced branch available on main. Therefore, I created a pull request. maybe you could do me the honor of a review?
> [/pull/3](https://github.com/brampf/fitskit/pull/3)

Hi... sorry never done this before... not sure what I have to do here exactly?  I am not real programmer... With SWIFT, I just put something together until it works.
